### ISSUE TITLE
Interactivité

### ISSUE THREAD

**Issue by nrojas1** [MShabi/Weapon-id-database-visualized#1]
Quand une région sur la carte est sélectionée, le dessin du réseaux à partir d'un click sur l'histogramme n'est pas effectuable. 
Reset du réseau non éxistant.
Manque de pop up lors du hover par dessus les noeud. Contenant des info sur les armes en question par ex.

**Comment by ipante** [comment]
Ces trois éléments constituent chacun une "issue". Merci de les séparer pour que je vous apporte des points de vue / solutions.
